title = "Anatole"
description = "A other zola theme"
base_url = "https://example.com"
compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
highlight_theme = "base16-ocean-light"

default_language = "en"

taxonomies = [
    {name = "tags"},
]

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[languages.zh.translations]
home = "首页"
about = "关于"
tags = "标签"
archive = "归档"
links = "友链"
date_format = "%Y-%m-%d"
next_page = "下一页"
last_page = "上一页"

[languages.de.translations]
about = "Info"
home = "Home"
tags = "Kategorien"
archive = "Archiv"
links = "Links"
date_format = "%d-%m-%Y"
next_page = "Nächste Seite"
last_page = "Vorherige Seite"

[extra.social]
github = ""
twitter = "w"
facebook = ""
instagram = "r"
dribbble = "t"
weibo = "y"
linkedin = ""
flickr = ""

[extra.show]
tags = true
links = true

